[package]
name = "antsy"
version = "0.1.0"
authors = ["shiveenpandita <shiveenpandita@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
serde = { version = "1.0.90", features=["derive"] }
